name          'garethr-kibana'
version       '0.2.0'
author        'garethr'
license       'Apache License, Version 2.0'
summary       'Module to manage the Kibana logstash interface'
project_page  'https://github.com/garethr/garethr-kibana'
dependency    'puppetlabs/vcsrepo', '>= 0.0.0'
dependency    'puppetlabs/git', '>= 0.0.0'
dependency    'puppetlabs/ruby', '>= 0.0.0'
dependency    'puppetlabs/stdlib', '>= 0.0.0'
dependency    'ploperations/bundler', '>= 0.0.0'
